import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import '@/styles/globals.css';
import 'react-toastify/dist/ReactToastify.css';

import { locales } from '@/constants/locales';
import { notFound } from 'next/navigation';
import { unstable_setRequestLocale } from 'next-intl/server';
import { NextIntlClientProvider, useMessages } from 'next-intl';
import Navigation from '@/partials/navigation';
import { CartProvider } from '@/context/cart.context';
import { ToastContainer } from 'react-toastify';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export function generateStaticParams() {
  return locales.map((locale) => ({ locale }));
}

export default function LocaleLayout({
  children,
  params: { locale },
}: Readonly<{
  children: React.ReactNode;
  params: { locale: string };
}>) {
  if (!locales.includes(locale)) {
    notFound();
  }

  unstable_setRequestLocale(locale);

  const messages = useMessages();

  return (
    <html lang={locale} className='dark h-full'>
      <body
        className={`${inter.className} flex min-h-full flex-row bg-background text-text`}
      >
        <NextIntlClientProvider messages={messages}>
          <CartProvider>
            <Navigation />
            {children}
            <ToastContainer theme={'dark'} position={'bottom-right'} />
          </CartProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
